### ISSUE TITLE
Error, your compressed code

### ISSUE THREAD

**Issue by liyinchigithub** [AlexcastroDev/json2excel-js#2]
![image](https://user-images.githubusercontent.com/19643260/79691261-fd03af00-8290-11ea-9a7c-8d78a1369a83.png)

**Comment by alexcastrodev** [comment]
Yeah, i can see...
Well, i updated the index.vue file, uncompress, and btw i remove unnecessary functions.

**Comment by alexcastrodev** [comment]
try to push again, and i hope it will work. it's working for me .

**Comment by alexcastrodev** [comment]
This issue will be closed.
